name: tentofree_web
description: "Tentofree Web"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.0

  flutter_localizations:
    sdk: flutter

  ###CORE PACKAGES##################
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  auto_route: ^8.3.0
  permission_handler: ^11.0.1
  stack_trace: ^1.11.0
  logger: ^2.0.2+1
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  connectivity_wrapper: ^1.1.4
  json_annotation: ^4.8.1
  timezone: ^0.9.2
  intl: ^0.19.0
  equatable: ^2.0.5
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  flutter_adaptive_scaffold: ^0.1.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  ##BUILDERS########################
  build_runner: ^2.4.8


  ###RESPONSIVE#####################
  responsive_builder: ^0.7.0
  get_it: ^7.6.7


  ###UI ENHANCEMENT#####################
  showcaseview: ^3.0.0
  skeletonizer: ^1.0.1
  badges: ^3.1.2
  pinput: ^5.0.0
  flutter_blurhash: ^0.8.2
  image_picker: ^1.1.2
  intl_phone_number_input: ^0.7.3+1
  flutter_side_menu: ^0.5.3
  country_code_picker: ^3.0.0
  multi_select_flutter: ^4.1.3
  flutter_native_splash: ^2.3.10
############HELPERS #################################
  file_picker: ^8.0.6
  url_launcher: ^6.2.2
  faker: ^2.1.0
  crypto: ^3.0.3
  uuid: ^4.1.0
  json_path: ^0.7.0
  package_info_plus: ^8.0.1
  geolocator: ^12.0.0
  path_provider: ^2.1.1
  url_strategy: ^0.3.0
  modal_bottom_sheet: ^3.0.0
  flutter_svg: ^2.0.10+1
  cart_stepper: ^4.3.0
  extended_phone_number_input: ^1.0.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.1.0
  custom_lint: ^0.6.4 # other lints depend on this
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  mocktail: ^1.0.1
  random_string: ^2.3.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.8
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
  #   - assets/svg/icons/
  #   - assets/svg/vectors/
  #   - assets/lottie/

  fonts:
      - family: Satoshi
        fonts:
          - asset: assets/fonts/Satoshi/Satoshi-Black.otf
          - asset: assets/fonts/Satoshi/Satoshi-BlackItalic.otf
          - asset: assets/fonts/Satoshi/Satoshi-Bold.otf
          - asset: assets/fonts/Satoshi/Satoshi-BoldItalic.otf
          - asset: assets/fonts/Satoshi/Satoshi-Italic.otf
          - asset: assets/fonts/Satoshi/Satoshi-Light.otf
          - asset: assets/fonts/Satoshi/Satoshi-LightItalic.otf
          - asset: assets/fonts/Satoshi/Satoshi-Medium.otf
          - asset: assets/fonts/Satoshi/Satoshi-MediumItalic.otf
          - asset: assets/fonts/Satoshi/Satoshi-Regular.otf
      - family: CustomIcons
        fonts:
          - asset: assets/fonts/CustomIcons.ttf
      - family: Helvetica
        fonts:
          - asset: assets/fonts/Helvetica.ttf
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  web: true